### ISSUE TITLE
Real-time chat platform

### ISSUE THREAD

**Issue by philpax** [setzer22/llama-rs#16]
It'd be good to be able to bounce ideas off each other in real-time instead of through issues for more moment-to-moment discussion. The popular choices in the Rust world are Discord and Zulip, from what I've seen; my preference is for Discord just because it's convenient. (I was considering creating one myself, but I figured that might be jumping the gun a little!)

**Comment by erlend-sh** [comment]
I’m in favor of Discord as well. There seems to be a lot of people from the Rust gamedev community here, for which Discord is currently the dominant platform.

Maybe a new channel could created in one of the existing servers, for easier cross-pollination. How about a dedicated channel on the [Burn](https://github.com/burn-rs/burn) discord? It has come up already as a potential integration:

> investigate using a Rust-native solution for the tensor manipulation (burn, ndarray, arrayfire, etc) to free it from the ggml dependency.

**Comment by philpax** [comment]
> How about a dedicated channel on the [Burn](https://github.com/burn-rs/burn) discord?

That would be reasonable, but I figure we shouldn't set up in their community until we're sure we're going to use them. It'd be a little rude to take up space if we end up using another library 😅

**Comment by setzer22** [comment]
I took the liberty to create a discord server :smile:  But we can move somewhere else if you folks think there's a better option: https://discord.gg/GBTh6HeG

**Comment by setzer22** [comment]
The discord is now featured in the README, so I think we can close this :smile:

**Comment by jmikedupont2** [comment]
> I took the liberty to create a discord server :smile:  But we can move somewhere else if you folks think there's a better option: https://discord.gg/GBTh6HeG

Please refresh
