### ISSUE TITLE
Renaming of types

### ISSUE THREAD

**Issue by philpax** [setzer22/llama-rs#17]
In #10, I re-exported the existing types with shorter names for the developer's benefit:
```rust
pub use llama::{
    GptVocab as Vocab, InferenceParams, LlamaHyperParams as HyperParams, LlamaModel as Model,
    OutputToken,
};
```
I suggest renaming the actual types to those names (the prefix is unnecessary if they're all in their own crates).

I'd also prefer `Vocabulary`, `Hyperparameters` and `InferenceParameters` over the existing names, but I'm not too fussed about those. I'm not sure what the going consensus is in the Rust ecosystem around shortening of words.

**Comment by setzer22** [comment]
I wasn't very fond of the names either, but during the porting phase I prioritized matching the C/C++ code as closely as possible over writing idiomatic Rust in many ways. I'd say now is a good time to start fixinf that, since we've diverged significantly from llama.cpp anyway 😄
