### ISSUE TITLE
Failing on windows 11 at cargo build --release

### ISSUE THREAD

**Issue by touhi99** [setzer22/llama-rs#24]
Hi, I am trying to figure out the problem, help will be great.

Failing on windows 11 at cargo build --release

Error message:

`Caused by:
  process didn't exit successfully: `C:\Users\touhidul.alam\Desktop\llama\llama-rs\target\release\build\ggml-raw-2925d7a622a7c725\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "/arch:AVX2" "-DNDEBUG" "-o" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\ggml/ggml.o" "-c" "ggml/ggml.c"
  cargo:warning=ggml/ggml.c: In function 'pthread_create':
  cargo:warning=ggml/ggml.c:53:49: warning: unused parameter 'unused' [-Wunused-parameter]
  cargo:warning=   53 | static int pthread_create(pthread_t* out, void* unused, thread_ret_t(*func)(void*), void* arg) {
  cargo:warning=      |                                           ~~~~~~^~~~~~
  cargo:warning=ggml/ggml.c: In function 'pthread_join':
  cargo:warning=ggml/ggml.c:64:49: warning: unused parameter 'unused' [-Wunused-parameter]
  cargo:warning=   64 | static int pthread_join(pthread_t thread, void* unused) {
  cargo:warning=      |                                           ~~~~~~^~~~~~
  cargo:warning=gcc.exe: warning: /arch:AVX2: linker input file unused because linking not done
  cargo:warning=gcc.exe: error: /arch:AVX2: linker input file not found: No such file or directory
  exit code: 1

  --- stderr

  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "/arch:AVX2" "-DNDEBUG" "-o" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\ggml/ggml.o" "-c" "ggml/ggml.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).`

**Comment by philpax** [comment]
Ah - didn't realise that people could build with GCC as well on Windows. Let me cook up a fix...

**Comment by philpax** [comment]
Can you test with https://github.com/setzer22/llama-rs/pull/25 ?

**Comment by setzer22** [comment]
Oops, lo

**Comment by touhi99** [comment]
Not yet :/ could be wrong from my end? I am not so familiar with rust and cargo yet unfortunately 

```
 Compiling ggml-raw v0.1.0 (C:\Users\touhidul.alam\Desktop\llama\llama-rs\ggml-raw)
The following warnings were emitted during compilation:

warning: ggml/ggml.c: In function 'pthread_create':
warning: ggml/ggml.c:53:49: warning: unused parameter 'unused' [-Wunused-parameter]
warning:    53 | static int pthread_create(pthread_t* out, void* unused, thread_ret_t(*func)(void*), void* arg) {
warning:       |                                           ~~~~~~^~~~~~
warning: ggml/ggml.c: In function 'pthread_join':
warning: ggml/ggml.c:64:49: warning: unused parameter 'unused' [-Wunused-parameter]
warning:    64 | static int pthread_join(pthread_t thread, void* unused) {
warning:       |                                           ~~~~~~^~~~~~
warning: ggml/ggml.c: In function 'quantize_row_q4_0':
warning: ggml/ggml.c:413:13: warning: unused variable 'pp' [-Wunused-variable]
warning:   413 |     uint8_t pp[QK/2];
warning:       |             ^~
warning: ggml/ggml.c: In function 'ggml_vec_dot_q4_0':
warning: ggml/ggml.c:1400:18: warning: unused variable 'countBlocks' [-Wunused-variable]
warning:  1400 |     const size_t countBlocks = nb;
warning:       |                  ^~~~~~~~~~~

error: failed to run custom build command for `ggml-raw v0.1.0 (C:\Users\touhidul.alam\Desktop\llama\llama-rs\ggml-raw)`

Caused by:
  process didn't exit successfully: `C:\Users\touhidul.alam\Desktop\llama\llama-rs\target\release\build\ggml-raw-2925d7a622a7c725\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "-pthread" "-mavx" "-mavx2" "-mfma" "-mf16c" "-msse3" "-DNDEBUG" "-o" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\ggml/ggml.o" "-c" "ggml/ggml.c"
  cargo:warning=ggml/ggml.c: In function 'pthread_create':
  cargo:warning=ggml/ggml.c:53:49: warning: unused parameter 'unused' [-Wunused-parameter]
  cargo:warning=   53 | static int pthread_create(pthread_t* out, void* unused, thread_ret_t(*func)(void*), void* arg) {
  cargo:warning=      |                                           ~~~~~~^~~~~~
  cargo:warning=ggml/ggml.c: In function 'pthread_join':
  cargo:warning=ggml/ggml.c:64:49: warning: unused parameter 'unused' [-Wunused-parameter]
  cargo:warning=   64 | static int pthread_join(pthread_t thread, void* unused) {
  cargo:warning=      |                                           ~~~~~~^~~~~~
  cargo:warning=ggml/ggml.c: In function 'quantize_row_q4_0':
  cargo:warning=ggml/ggml.c:413:13: warning: unused variable 'pp' [-Wunused-variable]
  cargo:warning=  413 |     uint8_t pp[QK/2];
  cargo:warning=      |             ^~
  cargo:warning=ggml/ggml.c: In function 'ggml_vec_dot_q4_0':
  cargo:warning=ggml/ggml.c:1400:18: warning: unused variable 'countBlocks' [-Wunused-variable]
  cargo:warning= 1400 |     const size_t countBlocks = nb;
  cargo:warning=      |                  ^~~~~~~~~~~
  exit code: 0
  cargo:rerun-if-env-changed=AR_x86_64-pc-windows-gnu
  AR_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_pc_windows_gnu
  AR_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-pc-windows-gnu
  ARFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_pc_windows_gnu
  ARFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  running: "ar" "cq" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\libggml.a" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\ggml/ggml.o"
  exit code: 0
  running: "ar" "s" "C:\\Users\\touhidul.alam\\Desktop\\llama\\llama-rs\\target\\release\\build\\ggml-raw-6f69f4f538ccd1b4\\out\\libggml.a"
  exit code: 0
  cargo:rustc-link-lib=static=ggml
  cargo:rustc-link-search=native=C:\Users\touhidul.alam\Desktop\llama\llama-rs\target\release\build\ggml-raw-6f69f4f538ccd1b4\out

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\touhidul.alam\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.62.0\./lib.rs:2402:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gordo1337** [comment]
> touhi99

Getting the same output as you

**Comment by philpax** [comment]
Okay, different issue, that's progress! I'm at work so I can't debug further, but it looks like it's trying to link in the clang runtime for some reason. Can you poke around `build.rs` / `cc`?

**Comment by philpax** [comment]
Still odd though... you shouldn't need clang for this.
