### ISSUE TITLE
Consider removing the `bindgen` dependency

### ISSUE THREAD

**Issue by philpax** [setzer22/llama-rs#26]
#22 and #24 show that `clang` is required as a build dependency because `bindgen` uses it to read in `ggml.h` and produce bindings. We should consider just writing the C bindings ourselves - it shouldn't be too difficult as long as we account for the idiosyncrasies (like #6)

**Comment by setzer22** [comment]
Hmmm, good point. But one thing that concerns me a bit with doing this manually is that if we mistype something in the bindings and call a function, that's UB. Isn't it?

**Comment by philpax** [comment]
It can be - I hope that doesn't happen, but it's definitely a possibility. We don't depend on too much from ggml as it is now anyway, right?
