### ISSUE TITLE
Deterministic generations

### ISSUE THREAD

**Issue by philpax** [setzer22/llama-rs#27]
Given the same seed and prompt, the same text should be generated. This will require us to implement a deterministic PRNG (instead of using thread_rng), and to allow specifying a seed. This should also assist in benchmarking.

**Comment by setzer22** [comment]
I would say, for the time being, determinism *given the same hardware and compiler version* is a good enough goal. Going beyond that and trying to make things deterministic across different kinds of hardware is probably going to negatively affect performance.

**Comment by philpax** [comment]
Aye, agreed with setzer - the primary thing I want is to be able to specify the same parameters on the same machine and get the same results. We can think about offering a "fully deterministic" mode later, but as you've mentioned madness lies that way.

**Comment by setzer22** [comment]
I think this can be closed since the rest of the work to get determinism is out-of-scope for now :+1:
