### ISSUE TITLE
build fails on arch linux

### ISSUE THREAD

**Issue by xi-pinmping** [setzer22/llama-rs#33]
Hi, building with arch linux fails and provides this output
```
warning: ggml/ggml.c: In function ‘quantize_row_q4_0’:
warning: ggml/ggml.c:413:13: warning: unused variable ‘pp’ [-Wunused-variable]
warning:   413 |     uint8_t pp[QK/2];
warning:       |             ^~
warning: ggml/ggml.c: In function ‘ggml_vec_dot_q4_0’:
warning: ggml/ggml.c:1422:18: warning: unused variable ‘countBlocks’ [-Wunused-variable]
warning:  1422 |     const size_t countBlocks = nb;
warning:       |                  ^~~~~~~~~~~
   Compiling llama-rs v0.1.0 (/home/user/opt/llama/llama-rs/llama-rs)
error[E0658]: let...else  statements are unstable
   --> llama-rs/src/lib.rs:492:17
    |
492 | /                 let Some(tensor) = model.tensors.get(&tensor_name)
493 | |                     else {
494 | |                         return Err(LoadError::UnknownTensor { tensor_name, path: part_path });
495 | |                     };
    | |______________________^
    |
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

For more information about this error, try rustc --explain E0658.
error: could not compile llama-rs due to previous error
```

**Comment by philpax** [comment]
You're using an old version of Rust - update to 1.65.0 or above.

**Comment by setzer22** [comment]
I wonder if there's a better way to enforce our MSRV so that cargo would complain if the rustc version is too old. These "*something* is unstable" messages are always so cryptic...

**Comment by philpax** [comment]
There is: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

We should check our MSRV and add that. If it's just `let else` though, it might not be too hard to drop the MSRV further 🤔

**Comment by setzer22** [comment]
For now I just made a very quick push specifying 1.65 as our MSRV to give a more accurate error message. We can later on try out different compiler versions to figure out the minimum (after removing the use of let..else)
