### ISSUE TITLE
When will we get Alpaca.rs?

### ISSUE THREAD

**Issue by leiserfg** [setzer22/llama-rs#42]

**Comment by philpax** [comment]
It already works 🙂 

Run it with [an Alpaca model](https://github.com/antimatter15/alpaca.cpp#get-started) and the Alpaca prompt, like the REPL PR does: #29.

**Comment by setzer22** [comment]
We already do! The alpaca-lora weights are compatible with this repo.

If you go to our discord server (see link in README) we even have a bot. Just type `/alpaca` and ask our alpaca a question! 😄
